---

env:
  global:
    - TWLIGHT_MISSING_MIGRATIONS=$(git ls-files --others --exclude-standard 'TWLight/*/migrations/*.py' | wc -l)

language: python

cache:
  directories:
    - ${HOME}/.cache/pip
    - ${HOME}/docker
# fix permissions before uploading cached docker images.
before_cache:
  - sudo service docker stop
  - sudo chown -R travis ${HOME}/docker

python:
  - 2.7

services:
  - docker

# Change location of docker image cache to a location that travis can use.
before_install:
  - sudo service docker stop
  - if [ "$(ls -A ${HOME}/docker)" ]; then echo "${HOME}/docker already set"; else sudo mv /var/lib/docker ${HOME}/docker; fi
  - sudo bash -c "echo 'DOCKER_OPTS=\"-H tcp://127.0.0.1:2375 -H unix:///var/run/docker.sock -g ${HOME}/docker\"' > /etc/default/docker"
  - sudo service docker start

install:
  - pip install coveralls
  - docker build --tag "wikipedialibrary/twlight:${TRAVIS_BRANCH}" .
  - docker-compose -f docker-compose.yml -f docker-compose.travis.yml up -d db twlight

# Initalize the app and test it.
script:
  - docker-compose exec twlight /app/bin/virtualenv_migrate.sh
  - docker-compose exec twlight /app/bin/virtualenv_translate.sh last-commit
  - docker-compose exec twlight /app/bin/virtualenv_test.sh

# Report on test coverage and push to production if the conditions are met.
after_success:
  - coveralls
  - .travis/./deploy.sh
  - .travis/./docker_push.sh
