---

env:
  global:
    - DJANGO_SETTINGS_MODULE=TWLight.settings.local
    - PIP_USE_MIRRORS=true
    - TWLIGHT_UNIXNAME=travis

language: python

cache: pip

python:
  - 2.7

addons:
  mariadb: '10.2'

services:
  - mysql

before_install:

# Install the dependencies.
install:
  - pip install -r requirements/wmf.txt

# Initalize the app and test it.
script:
  - .travis/./init.sh
  - python manage.py test --noinput

# Push to production if the conditions are met.
after_success:
  - .travis/./migrations.sh
  - .travis/./deploy.sh
