---

language: python

addons:
  mariadb: '10.2'

cache:
  directories:
    - ${HOME}/.cache/pip
    - docker

python:
  - 2.7

services:
  - docker
  - mysql

#before_install:

install:
  - bin/./twlight_mysql_init.sh
  - pip install coveralls
  - .travis/./docker_build.sh
  #- gzip -dc "docker/twlight_base.${TRAVIS_BRANCH}.tar.gz" | docker load || true
  #- gzip -dc "docker/twlight_build.${TRAVIS_BRANCH}.tar.gz" | docker load || true
  #- docker build --target twlight_base -t twlight_base .
  #- docker build --target twlight_build -t twlight_build .
  - docker-compose -f docker-compose.yml -f docker-compose.travis.yml up twlight -d
  #- docker ps -a
  #- docker save twlight_base | gzip > "docker/twlight_base.${TRAVIS_BRANCH}.tar.gz"
  #- docker save twlight_build | gzip > "docker/twlight_build.${TRAVIS_BRANCH}.tar.gz"

# Initalize the app and test it.
script:
  - docker-compose exec twlight /app/bin/virtualenv_migrate.sh
  - docker-compose exec twlight /app/bin/virtualenv_translate.sh last-commit
  - docker-compose exec twlight /app/bin/virtualenv_test.sh

# Report on test coverage and push to production if the conditions are met.
after_success:
  - coveralls
  - .travis/./deploy.sh
  - .travis/./docker_push.sh
