---

env:
  global:
    - TWLIGHT_MISSING_MIGRATIONS=$(git ls-files --others --exclude-standard 'TWLight/*/migrations/*.py' | wc -l)

language: minimal

services:
  - docker

# Build and run containers.
install:
  - .travis/./docker_compose.sh

# Initalize the app and test it.
script:
  - docker-compose exec twlight /app/bin/virtualenv_migrate.sh
  - docker-compose exec twlight /app/bin/virtualenv_translate.sh last-commit
  - docker-compose exec twlight /app/bin/virtualenv_test.sh

# Deploy changes if the conditions are met.
after_success:
  - .travis/./deploy.sh
