---

language: python

cache:
  directories:
    - ${HOME}/.cache/pip
    - docker

python:
  - 2.7

services:
  - docker

#before_install:

install:
  - pip install coveralls
  # Try to pull an existing image to warm the local build cache.
  #- docker pull "wikipedialibrary/twlight:${TRAVIS_BRANCH}"
  - gzip -dc docker/twlight_build.tar.gz | docker load || true
  - docker-compose -f docker-compose.yml -f docker-compose.travis.yml up --build -d
  - docker save twlight_build | gzip > docker/twlight_build.tar.gz

# Initalize the app and test it.
script:
  - docker-compose exec twlight /app/bin/virtualenv_migrate.sh
  - docker-compose exec twlight /app/bin/virtualenv_translate.sh last-commit
  - docker-compose exec twlight /app/bin/virtualenv_test.sh

# Report on test coverage and push to production if the conditions are met.
after_success:
  - coveralls
  - .travis/./deploy.sh
  - .travis/./docker_push.sh
