---

env:
  global:
    - TWLIGHT_MISSING_MIGRATIONS=$(git ls-files --others --exclude-standard 'TWLight/*/migrations/*.py' | wc -l)
    - BRANCH_TAG=branch_${TRAVIS_BRANCH//[^A-Za-z0-9]/_}
    - COMMIT_TAG=commit_${TRAVIS_COMMIT}
    - BUILD_TAG=build_${TRAVIS_BUILD_NUMBER}

language: minimal

services:
  - docker

install:
  # mirror images from docker.io to ${cr_server}.
  # Do this step if the job was fired by cron
  - if [ "${TRAVIS_EVENT_TYPE}" == "cron" ]; then .travis/./docker_mirror.sh; fi
  # Build and run containers.
  # Skip this step if the job was fired by cron
  - if [ "${TRAVIS_EVENT_TYPE}" != "cron" ]; then .travis/./docker_compose.sh; fi

# Initalize the app and test it.
# Skip these steps if the job was fired by cron
script:
  - if [ "${TRAVIS_EVENT_TYPE}" != "cron" ]; then docker-compose exec twlight /app/bin/virtualenv_migrate.sh; fi
  - if [ "${TRAVIS_EVENT_TYPE}" != "cron" ]; then docker-compose exec twlight /app/bin/virtualenv_translate.sh last-commit; fi
  - if [ "${TRAVIS_EVENT_TYPE}" != "cron" ]; then docker-compose exec twlight /app/bin/virtualenv_test.sh; fi

# Deploy changes if the conditions are met.
# Skip this steps if the job was fired by cron
after_success:
  - if [ "${TRAVIS_EVENT_TYPE}" != "cron" ]; then .travis/./deploy.sh; fi
