---

#env:
# - DOCKER_COMPOSE_VERSION=1.23.2

language: python

cache: pip

python:
  - 2.7

services:
  - docker

before_install:
  # Try to pull an existing image to warm the local build cache.
  - .travis/./docker_pull.sh

install:
  - pip install coveralls
  - docker-compose -f docker-compose.yml -f docker-compose.travis.yml up --build -d

# Initalize the app and test it.
script:
  - docker-compose exec twlight /app/bin/virtualenv_migrate.sh
  - docker-compose exec twlight /app/bin/virtualenv_translate.sh last-commit
  - docker-compose exec twlight /app/bin/virtualenv_test.sh

# Report on test coverage and push to production if the conditions are met.
after_success:
  - coveralls
  - .travis/./deploy.sh
  - .travis/./docker_push.sh
