---

language: python

cache: pip

python:
  - 2.7

services:
  - docker

before_install:

install:
  - pip install coveralls
  - docker-compose up

# Initalize the app and test it.
script:
  - docker-compose exec twlight /app/bin/virtualenv_migrate.sh
  - docker-compose exec twlight /app/bin/virtualenv_translate.sh last-commit
  - docker-compose exec twlight /app/bin/virtualenv_test.sh

# Report on test coverage and push to production if the conditions are met.
after_success:
  - coveralls
  - .travis/./deploy.sh
  - .travis/./docker_build.sh
  - .travis/./docker_push.sh
