---

version: '3.2'

services:
  db:
    image: mariadb:10
    ports:
      - "3306:3306"
    env_file:
      - ./conf/${TWLIGHT_ENV}.db.env
    environment:
      - MYSQL_USER
      - MYSQL_PASSWORD
  twlight:
    image: twlight:latest
    build: .
    command: bash -c "source /root/TWLight/bin/activate && cd /app && /root/TWLight/bin/gunicorn TWLight.wsgi"
    volumes:
      - type: bind
        source: ./backup
        target: /app/backup
      - type: bind
        source: ./media
        target: /app/media
      - type: bind
        source: ./TWLight
        target: /app/TWLight
      - type: bind
        source: ./logs
        target: /app/logs
    depends_on:
      - 'db'
    env_file:
      - ./conf/${TWLIGHT_ENV}.twlight.env
    environment:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - SECRET_KEY
      - TWLIGHT_GIT_REVISION
      - TWLIGHT_OAUTH_CONSUMER_KEY
      - TWLIGHT_OAUTH_CONSUMER_SECRET
  web:
    image: nginx:latest
    volumes:
      - type: bind
        source: ./conf/${TWLIGHT_ENV}.nginx.conf
        target: /etc/nginx/conf.d/default.conf
      - type: bind
        source: ./media
        target: /app/media
      - type: bind
        source: ./TWLight/templates/500
        target: /app/500
    ports:
      - "80:80"
    depends_on:
      - 'twlight'
