---

version: '3.1'

services:
  db:
    image: mariadb:10
    ports:
      - "3306:3306"
    env_file:
      - db.env

  twlight:
    build: .
    volumes:
      - backup:/mnt/backup:rw
    ports:
      - "80:80"
    depends_on:
      - 'db'
    env_file:
      - twlight.env

volumes:
  backup:
