---

version: '3.2'

services:
  db:
    image: mariadb:10
    volumes:
      - type: bind
        source: ./bin/twlight_mysql_init.sh
        target: /docker-entrypoint-initdb.d/twlight_mysql_init.sh
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD
      - DJANGO_DB_NAME
      - DJANGO_DB_USER
      - DJANGO_DB_PASSWORD
  twlight:
    image: twlight:latest
    build: .
    command: bash -c "source /root/TWLight/bin/activate && cd /app && /root/TWLight/bin/gunicorn TWLight.wsgi"
    volumes:
      - type: bind
        source: ./backup
        target: /app/backup
      - type: bind
        source: ./media
        target: /app/media
      - type: bind
        source: ./TWLight
        target: /app/TWLight
    depends_on:
      - 'db'
    env_file:
      - ./conf/${TWLIGHT_ENV}.twlight.env
    environment:
      - DJANGO_DB_NAME
      - DJANGO_DB_USER
      - DJANGO_DB_PASSWORD
      - SECRET_KEY
      - TWLIGHT_GIT_REVISION
      - TWLIGHT_OAUTH_CONSUMER_KEY
      - TWLIGHT_OAUTH_CONSUMER_SECRET
  web:
    image: nginx:latest
    volumes:
      - type: bind
        source: ./conf/${TWLIGHT_ENV}.nginx.conf
        target: /etc/nginx/conf.d/default.conf
      - type: bind
        source: ./media
        target: /app/media
      - type: bind
        source: ./TWLight/templates/500
        target: /app/500
    ports:
      - "80:80"
    depends_on:
      - 'twlight'
