---

version: '3.4'

services:
  twlight:
    image: quay.io/wikipedialibrary/twlight:local
    build:
      context: .
      cache_from:
        - quay.io/wikipedialibrary/twlight_base:branch_production
    env_file:
      - ./conf/travis.twlight.env
    environment:
      - TRAVIS_JOB_ID
      - TRAVIS_BRANCH
      - COVERALLS_REPO_TOKEN
