---

version: '3.4'

# Local environment should mount plaintext files as secrets
secrets:
  DJANGO_DB_NAME:
    file: ./secrets/DJANGO_DB_NAME
  DJANGO_DB_USER:
    file: ./secrets/DJANGO_DB_USER
  DJANGO_DB_PASSWORD:
    file: ./secrets/DJANGO_DB_PASSWORD
  MYSQL_ROOT_PASSWORD:
    file: ./secrets/MYSQL_ROOT_PASSWORD
  SECRET_KEY:
    file: ./secrets/SECRET_KEY
  TWLIGHT_OAUTH_CONSUMER_KEY:
    file: ./secrets/TWLIGHT_OAUTH_CONSUMER_KEY
  TWLIGHT_OAUTH_CONSUMER_SECRET:
    file: ./secrets/TWLIGHT_OAUTH_CONSUMER_SECRET
  TWLIGHT_EZPROXY_SECRET:
    file: ./secrets/TWLIGHT_EZPROXY_SECRET

services:
  twlight_base:
    image: quay.io/wikipedialibrary/twlight_base:local
    build:
      context: .
      target: twlight_base
      cache_from:
        - quay.io/wikipedialibrary/twlight_base:branch_production
  twlight_build:
    image: quay.io/wikipedialibrary/twlight_build:local
    build:
      context: .
      target: twlight_build
      cache_from:
        - quay.io/wikipedialibrary/twlight_base:local
        - quay.io/wikipedialibrary/twlight_base:branch_production
        - quay.io/wikipedialibrary/twlight_build:branch_production
  twlight:
    image: quay.io/wikipedialibrary/twlight:local
    build:
      context: .
      cache_from:
        - quay.io/wikipedialibrary/twlight_base:local
        - quay.io/wikipedialibrary/twlight_base:branch_production
        - quay.io/wikipedialibrary/twlight_build:local
        - quay.io/wikipedialibrary/twlight_build:branch_production
    env_file:
      - ./conf/travis.twlight.env
    environment:
      - TRAVIS_JOB_ID
      - TRAVIS_BRANCH
      - COVERALLS_REPO_TOKEN
    # Local environment should mount things from the code directory
    volumes:
      - type: bind
        source: .
        target: /app
  syslog:
    build:
      context: syslog
      cache_from:
        - quay.io/wikipedialibrary/twlight_syslog:branch_production
    environment:
      - MATOMO_FQDN=analytics-wikipedialibrary.wmflabs.org

