---

version: '3.2'

secrets:
  DJANGO_DB_NAME:
    external: true
  DJANGO_DB_USER:
    external: true
  DJANGO_DB_PASSWORD:
    external: true
  MYSQL_ROOT_PASSWORD:
    external: true
  SECRET_KEY:
    external: true
  TWLIGHT_OAUTH_CONSUMER_KEY:
    external: true
  TWLIGHT_OAUTH_CONSUMER_SECRET:
    external: true

services:
  db:
    volumes:
      - type: bind
        source: ./db/data
        target: /var/lib/mysql
  twlight:
    env_file:
      - ./conf/staging.twlight.env
    volumes:
      - type: bind
        source: /data/project/staging
        target: /app/backup
  web:
    volumes:
      - type: bind
        source: ./conf/staging.nginx.conf
        target: /etc/nginx/conf.d/default.conf
