---

version: '3.2'

services:
  db:
    image: mariadb:10
    ports:
      - "3306:3306"
    env_file:
      - db.env

  twlight:
    build: .
    volumes:
      - type: bind
        source: ./backup
        target: /app/backup
      - type: bind
        source: ./media
        target: /app/media
    ports:
      - "80:80"
    depends_on:
      - 'db'
    env_file:
      - twlight.env
